name: Check versions

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-versions:
    strategy:
      matrix:
        container: 
          - alt:sisyphus
          - alt:p10
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: install packages
        run: |
          apt-get update && apt-get -y install eepm git github-cli
          epm update
    
      - uses: actions/checkout@v3

      - name: Repack
        run: |
          ./repack.sh
        env:
          GH_TOKEN: ${{ github.token }}
